import {
  ADD_ACTIVITY_SCHEDULE_ITEM,
  DELETE_ACTIVITY_SCHEDULE_ITEM,
  GET_ACTIVITY_SCHEDULE_ITEM_SCHEMA_ADD,
  GET_ACTIVITY_SCHEDULE_ITEM_SCHEMA_COLUMNS,
  GET_ACTIVITY_SCHEDULE_ITEM_SCHEMA_UPDATE,
  GET_ACTIVITY_SCHEDULE_ITEMS_MY,
  UPDATE_ACTIVITY_SCHEDULE_ITEM,
} from '@/api/packageItems';
import CrudTable from '@/generic/components/crudTable';

export default function PackageItems() {
  return (
    <CrudTable
      title="Package items"
      GET={GET_ACTIVITY_SCHEDULE_ITEMS_MY}
      ADD={ADD_ACTIVITY_SCHEDULE_ITEM}
      UPDATE={UPDATE_ACTIVITY_SCHEDULE_ITEM}
      ARCHIVE={DELETE_ACTIVITY_SCHEDULE_ITEM}
      getJsonFormDataAdd={GET_ACTIVITY_SCHEDULE_ITEM_SCHEMA_ADD}
      getJsonFormDataUpdate={GET_ACTIVITY_SCHEDULE_ITEM_SCHEMA_UPDATE}
      getJsonFormColumnsAndFilters={GET_ACTIVITY_SCHEDULE_ITEM_SCHEMA_COLUMNS}
      tableStyleTw="max-w-[99%] mx-auto"
    />
  );
}
